services:
  # Backend API service
  - type: web
    name: gigy-backend
    env: node
    region: singapore
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # This will be set manually in the Render dashboard for security
      - key: JWT_SECRET
        sync: false # This will be set manually in the Render dashboard for security
      - key: CLOUDINARY_CLOUD_NAME
        sync: false # Set this in the dashboard
      - key: CLOUDINARY_API_KEY
        sync: false # Set this in the dashboard
      - key: CLOUDINARY_API_SECRET
        sync: false # Set this in the dashboard
    autoDeploy: true

  # Frontend React app
  - type: static
    name: gigy-frontend
    env: static
    buildCommand: cd frontend && npm install && REACT_APP_API_URL=https://gigy-backend.onrender.com npm run build
    staticPublishPath: frontend/build
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
